Repository Arquisoft/wichat_es5a, pull requests merged in 2025-04, with the labels that each got.

#195 Hechos los test del Login
  webapp/src/components/Login/Login.test.js
Labels: Front-end, Test

#181 Historial completado
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/openapi.yaml
  historyservice/history-contestModel.js
  historyservice/history-service.js
  users/userservice/user-model.js
  users/userservice/user-service.js
  webapp.zip
  webapp/public/favicon.ico
  webapp/src/components/ContestHistory/ContestHistory.js
  webapp/src/components/Game/Game.js
  webapp/src/components/History/History.js
  webapp/src/components/ReactComponents/HistoryText.js
  webapp/src/components/Temporizador/Temporizador.js
  webapp/src/components/Temporizador/Temporizador.test.js
  webapp/src/routers/AppRouter.js
  wikiservice/wiki-service.js
Labels: Documentation, Front-end, Back-end, BBDD

#207 Tests varios
  gatewayservice/gateway-service.test.js
  historyservice/history-service.test.js
  webapp/src/components/ContestHistory/ContestHistory.test.js
  webapp/src/components/History/History.test.js
Labels: Test

#213 Documentación para 1.0, faltaría mirar el apartado 7 mejor
  docs/images/BuildingBlock2.png
  docs/images/DiagramaDespliegue.png
  docs/src/01_introduction_and_goals.adoc
  docs/src/02_architecture_constraints.adoc
  docs/src/03_context_and_scope.adoc
  docs/src/04_solution_strategy.adoc
  docs/src/07_deployment_view.adoc
  docs/src/11_technical_risks.adoc
Labels: Documentation, Corrección

#261 Añadidos test del Game de colores y botón siguiente
  webapp/src/components/Game/Game.test.js
Labels: Front-end, Test

#262 Deshabilitado el botón del chat antes de que cargue la primera pregunta
  webapp/src/components/Game/Game.js
Labels: bug, Front-end

#271 Añadido correo al AddUser, como comprobaciones a este y al Login
  users/userservice/user-model.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/src/components/AddUser/AddUser.js
  webapp/src/components/AddUser/AddUser.test.js
  webapp/src/components/Login/Login.js
  webapp/src/components/Login/Login.test.js
  webapp/src/i18n.js
Labels: Corrección, Front-end, Back-end, BBDD

#304 Actualización de los diagramas del punto 6 de la documentación
  docs/src/06_runtime_view.adoc
Labels: Documentation

#277 Ranking y historial del usuario hechos
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  historyservice/history-service.js
  package-lock.json
  package.json
  users/userservice/user-model.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/ContestHistory/ContestHistory.js
  webapp/src/components/ContestHistory/ContestHistory.test.js
  webapp/src/components/Game/Game.js
  webapp/src/components/Game/Game.test.js
  webapp/src/components/History/History.js
  webapp/src/components/History/History.test.js
  webapp/src/components/Home/Home.js
  webapp/src/components/Home/Home.test.js
  webapp/src/components/Profile/Profile.js
  webapp/src/components/Profile/Profile.test.js
  webapp/src/components/Ranking/Ranking.js
  webapp/src/components/Ranking/Ranking.test.js
  webapp/src/components/ReactComponents/HistoryHeader.js
  webapp/src/components/ReactComponents/HistoryTableHeader.js
  webapp/src/components/ReactComponents/HistoryText.js
  webapp/src/components/ReactComponents/LargeButton.js
  webapp/src/components/Temporizador/Temporizador.js
  webapp/src/i18n.js
  webapp/src/routers/AppRouter.js
Labels: Front-end, Back-end

#147 Tests unitarios de history y wiki service añadidos en el build y release
  .github/workflows/build.yml
  .github/workflows/release.yml
  historyservice/history-service.test.js
  wikiservice/wiki-service.test.js
Labels: Despliegue, Back-end, Test

#311 Docu api
  gatewayservice/openapi.yaml
  users/authservice/auth-service.js
Labels: Documentation, Back-end

#316 Mostrar puntuación al final del juego
  webapp/src/components/Points/Points.js
  webapp/src/routers/PrivateRouter.js
Labels: Front-end

#321 Añadida alguna internacionalización que faltaba y arreglados los tokens (otra vez)
  users/authservice/auth-service.js
  users/userservice/user-service.js
  webapp/src/components/Ranking/Ranking.js
  webapp/src/components/Ranking/Ranking.test.js
  webapp/src/i18n.js
Labels: bug🐛, Back-end</>

#325 Botón back y interfaz home
  webapp/src/components/Credits/Credits.js
  webapp/src/components/GameMode/GameMode.js
  webapp/src/components/History/History.js
  webapp/src/components/Home/Home.js
  webapp/src/components/Ranking/Ranking.js
Labels: Front-end💻

#330 Subido el timeout y quitado un tests e2e
  webapp/e2e/features/profile.feature
  webapp/e2e/jest.config.js
  webapp/e2e/steps/game.steps.js
  webapp/e2e/steps/login-form.steps.js
  webapp/e2e/steps/profile.steps.js
  webapp/e2e/steps/register-form.steps.js
Labels: Test🧪

#329 Quitada duracion de los token
  users/authservice/auth-service.js
  users/userservice/user-service.js
Labels: Back-end</>

#338 Arreglo del prometheus
  gatewayservice/monitoring/prometheus/Dockerfile
  gatewayservice/monitoring/prometheus/prometheus.yml
Labels: bug🐛, Back-end</>

#341 Organizados botones del perfil
  webapp/src/components/Profile/Profile.css
  webapp/src/components/Profile/Profile.js
Labels: Front-end💻

#343 Actualizado apiDoc
  gatewayservice/openapi.yaml
Labels: Documentation📚

#350 Diagramas actualizados
  docs/images/BuildingBlock2.png
  docs/images/DiagramaDespliegue.png
  docs/src/03_context_and_scope.adoc
Labels: Documentation📚

#352 Cambios hechos en la documentación y en el resultado del Gatling
  docs/images/Carga1.png
  docs/images/Carga2.png
  docs/images/Diagrama de clases.png
  docs/images/DiagramaDeClases.png
  docs/src/08_concepts.adoc
  docs/src/12_testing.adoc
  gatling/Resultados/Prueba_120_usuarios/index.html
  gatling/Resultados/Prueba_120_usuarios/js/all_sessions.js
  gatling/Resultados/Prueba_120_usuarios/js/global_stats.json
  gatling/Resultados/Prueba_120_usuarios/js/stats.js
  gatling/Resultados/Prueba_120_usuarios/js/stats.json
  gatling/Resultados/Prueba_120_usuarios/req_adduser-516110316.html
  gatling/Resultados/Prueba_120_usuarios/req_cargar-guardado-2032153744.html
  gatling/Resultados/Prueba_120_usuarios/req_cargar-historia--923139789.html
  gatling/Resultados/Prueba_120_usuarios/req_cargar-juego-69207622.html
  gatling/Resultados/Prueba_120_usuarios/req_cargar-llm-1407892305.html
  gatling/Resultados/Prueba_120_usuarios/req_cargar-login-70877901.html
  gatling/Resultados/Prueba_120_usuarios/req_cargar-pa-gina---1356823852.html
  gatling/Resultados/Prueba_120_usuarios/req_enviar-datos-de--1287205580.html
  gatling/Resultados/Prueba_120_usuarios/req_enviar-opciones--612035756.html
  gatling/Resultados/Prueba_120_usuarios/req_favicon-ico-242292667.html
  gatling/Resultados/Prueba_120_usuarios/req_login-73596745.html
  gatling/Resultados/Prueba_120_usuarios/req_ma-s-opciones-d-1014265794.html
  gatling/Resultados/Prueba_120_usuarios/req_main-5041211b-c--633278382.html
  gatling/Resultados/Prueba_120_usuarios/req_main-9eae964b-j-1905004647.html
  gatling/Resultados/Prueba_120_usuarios/req_obtener-histori--714028474.html
  gatling/Resultados/Prueba_120_usuarios/req_preflight-optio-1478848524.html
  gatling/Resultados/Prueba_120_usuarios/req_request-1-693933697.html
  gatling/Resultados/Prueba_120_usuarios/req_respuesta-llm-2144267853.html
  gatling/Resultados/Prueba_120_usuarios/req_segunda-carga-d-101359878.html
  gatling/Resultados/Prueba_120_usuarios/simulation.log
Labels: Documentation📚, Test🧪
