Repository Arquisoft/wichat_es5a, pull requests merged in 2025-03, with the labels that each got.

#83 Correcion punto 7
  docs/images/07-diagramaDespliegue.png
  docs/src/07_deployment_view.adoc
Labels: Documentation, Corrección

#91 Ventana home
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/AddUser/AddUser.js
  webapp/src/components/AddUser/AddUser.test.js
  webapp/src/components/Components.css
  webapp/src/components/Credits/Credits.js
  webapp/src/components/Error/404.png
  webapp/src/components/Error/Error.js
  webapp/src/components/Home/Home.js
  webapp/src/components/Login.js
  webapp/src/components/Login/Login.js
  webapp/src/components/Login/Login.test.js
  webapp/src/components/Points/Points.js
  webapp/src/components/Profile/Profile.js
  webapp/src/routers/AppRouter.js
  webapp/src/routers/AuthRoute.js
  webapp/src/routers/PrivateRouter.js
Labels: Front-end

#104 Almacenamiento de preguntas y respuestas en base de datos
  docker-compose.yml
  docs/src/01_introduction_and_goals.adoc
  docs/src/04_solution_strategy.adoc
  docs/src/08_concepts.adoc
  docs/src/10_quality_requirements.adoc
  docs/src/12_glossary.adoc
  gatewayservice/gateway-service.js
  wikiservice/package-lock.json
  wikiservice/package.json
  wikiservice/question-model.js
  wikiservice/wiki-query.js
  wikiservice/wiki-service.js
Labels: WikiData, Back-end

#109 Arreglados tests de una vez
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/AddUser/AddUser.js
  webapp/src/components/AddUser/AddUser.test.js
  webapp/src/components/Game/Game.js
  webapp/src/components/Home/Home.js
  webapp/src/components/Login/Login.js
  webapp/src/components/Login/Login.test.js
  webapp/src/components/Points/Points.js
  webapp/src/routers/AppRouter.js
  webapp/src/setupTests.js
Labels: bug, Test

#111 Arreglados warnings
  webapp/src/components/AddUser/AddUser.js
  webapp/src/components/Error/Error.js
  webapp/src/components/Game/Game.js
  webapp/src/components/Login/Login.js
  webapp/src/components/Points/Points.js
  webapp/src/components/Profile/Profile.js
  webapp/src/components/Temporizador/Temporizador.js
Labels: bug

#119 Arreglo de algunas test y arreglo temporal del registro de usuario
  users/userservice/user-service.js
  webapp/e2e/steps/register-form.steps.js
Labels: bug, Test, BBDD

#120 Tests registro
  webapp/e2e/steps/register-form.steps.js
Labels: Corrección, Test

#121 A la tercera va la vencida
  webapp/e2e/steps/register-form.steps.js
  webapp/src/components/AddUser/AddUser.js
Labels: Corrección, Test

#122 Ahora si que si jurao
  webapp/e2e/steps/register-form.steps.js
  webapp/src/components/AddUser/AddUser.js
Labels: Corrección, Test

#123 Cambiar funcionalidad para que pase el test
  webapp/e2e/steps/register-form.steps.js
  webapp/src/components/AddUser/AddUser.js
Labels: Corrección, Test

#118 Añadido componente LargeButton
  webapp/src/components/AddUser/AddUser.js
  webapp/src/components/Credits/Credits.js
  webapp/src/components/Home/Home.js
  webapp/src/components/Login/Login.js
  webapp/src/components/Points/Points.js
  webapp/src/components/Profile/Profile.js
  webapp/src/components/ReactComponents/LargeButton/LargeButton.js
Labels: Front-end

#127 Más arreglos
  .github/workflows/release.yml
  users/userservice/user-service.test.js
  webapp/src/components/Login/Login.js
Labels: bug, Despliegue, Test

#144 Añadido comando automatico
  package-lock.json
  package.json
Labels: Despliegue, Back-end

#145 Tests gateway service
  .github/workflows/release.yml
  docker-compose.yml
  gatewayservice/gateway-service.test.js
  historyservice/.dockerignore
  historyservice/Dockerfile
  historyservice/README.md
  historyservice/history-service.js
  historyservice/package-lock.json
  historyservice/package.json
Labels: Despliegue, Back-end, Test

#150 History service
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  historyservice/history-questionModel.js
  historyservice/history-service.js
  historyservice/history-userModel.js
  package.json
  webapp/src/components/AddUser/AddUser.js
  webapp/src/components/Credits/Credits.js
  webapp/src/components/Error/Error.js
  webapp/src/components/History/History.js
  webapp/src/components/Home/Home.js
  webapp/src/components/Login/Login.js
  webapp/src/components/Points/Points.js
  webapp/src/components/Profile/Profile.js
  webapp/src/components/ReactComponents/CustomH1.js
  webapp/src/components/ReactComponents/LargeButton.js
  webapp/src/routers/AppRouter.js
Labels: Front-end, Back-end, BBDD

#164 Nuevas comandos automaticos
  package.json
Labels: Back-end

#185 Añadidos metodos /health a todos los servicios
  gatewayservice/gateway-service.js
  historyservice/history-service.js
  llmservice/llm-service.js
  users/authservice/auth-service.js
  users/userservice/user-service.js
  wikiservice/wiki-service.js
Labels: Back-end
