Repository Arquisoft/wichat_es5a, pull requests merged in 2025-02, with the labels that each got.

#52 Añadidos 5 términos al glosario.
  docs/src/12_glossary.adoc
Labels: documentation

#49 Arreglado el diagrama técnico
  docs/src/03_context_and_scope.adoc
Labels: documentation, Corrección

#53 Añadidos conceptos Under the hood y corregido errores
  docs/src/08_concepts.adoc
Labels: documentation, Corrección

#48 Documento 11 de la documentación hecho.
  docs/src/11_technical_risks.adoc
Labels: documentation

#51 Punto9 terminado.
  docs/images/DiagramaAtributosCalidad.png
  docs/src/09_architecture_decisions.adoc
  docs/src/10_quality_requirements.adoc
Labels: documentation

#46 Información añadida al punto 2 de la documentación del proyecto.
  docs/src/02_architecture_constraints.adoc
Labels: documentation, Corrección

#50 Información añadida al punto 10 de la documentación del proyecto
  docs/images/arbol-calidad.png
  docs/src/10_quality_requirements.adoc
Labels: documentation

#79 Corrección punto 1 y 3 de la documentacion
  docs/src/01_introduction_and_goals.adoc
  docs/src/03_context_and_scope.adoc
Labels: Documentation, Corrección
